# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 621)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 50, 171, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 380, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 70, 261, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 200, 171, 16))
        self.label_4.setObjectName("label_4")
        self.dcmtgrs = QtWidgets.QPushButton(self.centralwidget)
        self.dcmtgrs.setGeometry(QtCore.QRect(100, 110, 101, 28))
        self.dcmtgrs.setObjectName("dcmtgrs")
        self.benzerlik = QtWidgets.QLineEdit(self.centralwidget)
        self.benzerlik.setGeometry(QtCore.QRect(90, 230, 113, 22))
        self.benzerlik.setObjectName("benzerlik")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 270, 151, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(420, 30, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(420, 200, 151, 16))
        self.label_8.setObjectName("label_8")
        self.skor = QtWidgets.QLineEdit(self.centralwidget)
        self.skor.setGeometry(QtCore.QRect(90, 300, 113, 22))
        self.skor.setObjectName("skor")
        self.createozet = QtWidgets.QPushButton(self.centralwidget)
        self.createozet.setGeometry(QtCore.QRect(270, 260, 93, 28))
        self.createozet.setObjectName("createozet")
        self.ozetgrs = QtWidgets.QPushButton(self.centralwidget)
        self.ozetgrs.setGeometry(QtCore.QRect(100, 420, 93, 28))
        self.ozetgrs.setObjectName("ozetgrs")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(420, 340, 151, 16))
        self.label_11.setObjectName("label_11")
        self.rouge = QtWidgets.QLabel(self.centralwidget)
        self.rouge.setGeometry(QtCore.QRect(420, 480, 101, 16))
        self.rouge.setObjectName("rouge")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(420, 70, 275, 100))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(420, 240, 275, 75))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(420, 380, 275, 75))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(420, 510, 275, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Doküman girişi için tıklayınız."))
        self.label_2.setText(_translate("MainWindow", "Özet girişi için tıklayınız."))
        self.label_3.setText(_translate("MainWindow", "(Doküman içerisinde özet bulunmamalıdır.)"))
        self.label_4.setText(_translate("MainWindow", "Cümle Benzerliği Tresholdu"))
        self.dcmtgrs.setText(_translate("MainWindow", "Doküman Girişi"))
        self.label_5.setText(_translate("MainWindow", "Cümle Skoru Tresholdu"))
        self.label_6.setText(_translate("MainWindow", "Doküman İçeriği:"))
        self.label_8.setText(_translate("MainWindow", "Oluşturulan Özet İçeriği:"))
        self.createozet.setText(_translate("MainWindow", "Özet Oluştur"))
        self.ozetgrs.setText(_translate("MainWindow", "Özet Girişi"))
        self.label_11.setText(_translate("MainWindow", "Gerçek Özet İçeriği:"))
        self.rouge.setText(_translate("MainWindow", "ROUGE Skoru:"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
